# Generated by Django 3.1.6 on 2021-02-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0002_auto_20210210_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='cep',
            field=models.CharField(max_length=8),
        ),
    ]
